### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xland** [jpush/cordova-plugin-janalytics#5]
cordova -version:
8.1.2 (cordova-lib@8.1.1)

error info：
Installing "cordova-plugin-janalytics" for android
Plugin dependency "cordova-plugin-jcore@1.2.6" already fetched, using that version.
Dependent plugin "cordova-plugin-jcore" already installed on android.
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-janalytics': TypeError: Uh oh!
Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at copyNewFile (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/lib/pluginHandlers.js:258:28)
    at install (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/project/ShouLaShou/src/jianghu-cordova/platforms/android/cordova/node_modules/q/q.js:863:30)
Uh oh!
Path must be a string. Received undefined

**Comment by JoshLipan** [comment]
Update plugin to [v1.4.0](https://github.com/jpush/cordova-plugin-janalytics/releases/tag/v1.4.0)
